dbt_k8_demo:
  outputs:
    default:
      type: bigquery
      dataset: dbt_k8_demo # CHANGE THIS
      fixed_retries: 1
      location: europe-west2
      method: oauth
      priority: interactive
      project: danel-dbt-project # CHANGE THIS
      threads: 5
      timeout_seconds: 300
      impersonate_service_account: dbt-jobs-user@danel-dbt-project.iam.gserviceaccount.com
